### ISSUE TITLE
support widget_base_dimensions

### ISSUE THREAD

**Issue by nghiado** [tiberiuzuld/angular-gridster2#12]
For  a dashboard layout, sometimes I need to set a specific width/height for the widgets.
I found that there is no way to set the widget_base_dimensions when use your lib.
Can you support it? It's a blocker to us in order to use your lib in our project.
http://dsmorse.github.io/gridster.js/#widget_base_dimensions_opt

**Comment by tiberiuzuld** [comment]
Hi @nghiado ,
Setting a fixed width and height different for each widget will override the current columns/rows system on how the grid is calculated. This could create issues of overlap with the surrounding widgets.

Even setting a single, grid wide, min height and width for all widgets, will still cause issues because each widget calculations from cols/rows to pixel is done by each widget in part independent of the neighbours or grid.

The idea of this implementation is to keep things as flexible as possible so the grid can adapt on any screen size without to many constraints to cause conflicts.

I think that setting a min number of cols/rows for each widget will be more acceptable, than to set a min height/width in px. 

After I implement the rest of suggestions you made, I will think again about this and see if maybe I get a different way to implement it.

**Comment by nghiado** [comment]
@tiberiuzuld  how about provide a setting to control the width of col and the height of row  across the grid
For example, I can design all my widgets based on a minimum size of 1 col and 1 row (ie. 25*25) other widgets will snap to closest grid size (x*25)*(y*25)

**Comment by tiberiuzuld** [comment]
Providing a grid row/col size will be more easily to added and will not affect how each widget is calculated.
Yes this may work.
Will add another option in `gridType = 'fixed'` and 
options only for this grid type: `rowSize: 50` , `colSize: 50`
This will be ok for you ?

**Comment by nghiado** [comment]
I don't think it shoud apply only to 'fixed' grid type. for a big dashboard with many custom widgets, I have to use 'scrollVertical' type.

**Comment by tiberiuzuld** [comment]
The `gridType: 'fixed'` will have both scroll horizontal and vertical since the widgets will not set size depending of the width or height of the space they have.

So in this case the widgets size will be fixed in pixels depending of the number of columns and rows they have. 

If they exceed the space the grid has the vertical and/or horizontal scroll will appear.

**Comment by nghiado** [comment]
@tiberiuzuld Looks like there are bug with gridType: 'fixed' based on your explaination.
I don't see any thing like that except all widgets are scaled down to make them 'fit' into the screen.
That's why I could not use it at the first time.
<img width="1388" alt="screen shot 2017-03-24 at 9 44 33 am" src="https://cloud.githubusercontent.com/assets/1259031/24299293/b8bc005c-1076-11e7-99e8-aaa4787a8431.png">

**Comment by tiberiuzuld** [comment]
@nghiado Didn't implement the `gridType:'fixed'` yet. Will do as soon as I have some free time.

The mode you have selected is  `gridType:''fit' which will calculate the widgets cols/rows depending on height and width.

**Comment by nghiado** [comment]
@tiberiuzuld ah, my bad :), can't wait to test your updates

**Comment by tiberiuzuld** [comment]
Implemented in v2.3.0.
