### ISSUE TITLE
can support free mode for drag and drop?

### ISSUE THREAD

**Issue by LE88I5** [tiberiuzuld/angular-gridster2#144]
like https://github.com/mauricius/vue-draggable-resizable

**Comment by tiberiuzuld** [comment]
Hi @LE88I5 ,
No because will defeat the purpose of having a grid and items aligned, not overlapping etc.

If you want to be able to move an item for each pixel you can increase the number of columns/rows for each pixel on the screen and pretty much have something similar, but with collision detection.

Thanks,

**Comment by LE88I5** [comment]
@tiberiuzuld 
Thank you, I see.
