### ISSUE TITLE
Zoom in/Zoom out

### ISSUE THREAD

**Issue by josevi86** [tiberiuzuld/angular-gridster2#171]
¿It is possible to zoom in or zoom out the gridster? It would be awesome the posibility of zoom in/zoom out, only the grid, with the wheel of the mouse.

Thanks in advance.

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
I don't see the use case for this?
Do you need to pan also?
What use case is not covered by browser zoom ?
And you need mode wheel to scroll when grid vertical.

Thanks

**Comment by josevi86** [comment]
We are using the grid to show some graphics. The user could have a very big graphic, and another very small. It is true that you can expand it or reduce it manually, also we would configure gridster with more columns and rows, but maybe would be useful provide zoom functionality, bringing the posibility of 
zooming the smallest items.

In this screenshot, the first widget (widgeta) is to small, and would be great to zoom in its zone.

![gridster](https://user-images.githubusercontent.com/9534310/33368858-1bb19316-d4f3-11e7-9ad3-c6468e641eb9.png)

The pan would not be strictly necessary, maybe we could zoom in the zone that is aimed by the mouse pointer and using the wheel up, and zoom out with the wheel down.

The browser zoom is useful, but it increases all the screen, and would be desirable only zoom the grid  (Google Maps style, when you zoom in the map, the toolbars are not zooming).

Thanks so much!

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,

Well in your case it may work but:
1. Can't use only mouse wheel since that is used when you have a vertical grid type.
2. Some people may have scroll inside widgets or zoom on charts from widgets.
3. This zoom you want to increase the width of columns and height of rows ? Then it will no longer fit the available space. 
4. How the user will know that he can zoom in ?
5. If the user has mouse over widget he will expect to zoom inside he chart not grid ?
6. If you have small charts the labels will overlap when the zoom is initial. User will think something is broken.

I don't think your use case fits a good user experience and a overall good feature for the grid.

Thanks

**Comment by josevi86** [comment]
Yes, i totally understand you. I will think a little more about this.

For now, we discard this zoom.

Thanks again! I really appreciate your good work.
