### ISSUE TITLE
Multiple breakpoints

### ISSUE THREAD

**Issue by yahyazini** [tiberiuzuld/angular-gridster2#173]
Is there a way I can support multiple breakpoints? 

- On Desktop show 3 cols
- On Tablet show 2 cols
- On Mobile show 1 col

Thank you

**Comment by tiberiuzuld** [comment]
Hi @yahyazini ,
The scope of this library is not to solve this use case, since the user can set whatever position and size to the grid with drag and resize of the items if you don't hard limit the users.

If you really want to limit to those 3 breakpoints why use the library at all ?

Anyway you can achieve your desired setup by two methods:
1. Use 3 separate options and items config depending on screen size.
2. Use only one configuration. But with higher mobileBreakpoint.
And use case to override the grid mobile class with your own css declaring how many columns you want for each resolution, by using [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and media queries.

Thanks
