### ISSUE TITLE
Show-Hide widgets?

### ISSUE THREAD

**Issue by cpandya** [tiberiuzuld/angular-gridster2#200]
Hi @tiberiuzuld 
Is it possible to show-hide widgets?

**Comment by tiberiuzuld** [comment]
Hi @cpandya ,
There is no option for that.
You can implement your own logic and use ngclass or [hidden].
Don't really recommend it though. Since if the user tries to drag/resize over will not know why.
Or you can completely remove the widget from grid and insert it back on show. But to be sure of no overlap try using options.api.getNextPosiblePosition

Let me know if this will help in your use case.
Thanks
