### ISSUE TITLE
grid item state

### ISSUE THREAD

**Issue by kirtiesl** [tiberiuzuld/angular-gridster2#226]
Hi,
is there any way to save grid item sequences after drag and drop?
any help will be appreciated.

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
What do you mean by grid item sequences ?

**Comment by kirtiesl** [comment]
Hi,

I want to implement functionality to save the widgets order on drag on drop of any widget. So, when my page is loaded for the next time it will arrange the widgets in the same order.

**Comment by tiberiuzuld** [comment]
You should use the callback:
```javascript
 itemChangeCallback: undefined,  // callback to call for each item when is changes x, y, rows, cols.
  // Arguments: gridsterItem, gridsterItemComponent
``` 

You can find the api on [Readme.md](https://github.com/tiberiuzuld/angular-gridster2)

**Comment by mischkl** [comment]
I think I might have an idea what @kirtiesl means because we have a similar use case. We have a list of items and the gridster component just takes the list and lays it out, with `compactType: 'compactUp&Left'`. If we change the input list, the layout changes. Ideally we would like the opposite to also be possible - for changes in the layout to change the order of the list, so that the new list oder can be saved for later.

**Comment by tiberiuzuld** [comment]
Hi @mischkl ,
For your use case in the item change callback you need to order your list of items by x and y.
Then save the order to your DB.
For sort you can use the plain old js Array.sort with a compare function or something in angular like a Pipe.

**Comment by mischkl** [comment]
OK so if I understand I we need to save a list of items that each have an X and Y, which can then be mapped to GridItems. Seems easy enough, although for responsive layouts I guess it could cause issues. Luckily we don't need to cover mobile use cases, though.

**Comment by tiberiuzuld** [comment]
For mobile there is the mobileBreakpoint. under that number the items will be displayed one after another.
