### ISSUE TITLE
Grid without vertical scroll 

### ISSUE THREAD

**Issue by skarface** [tiberiuzuld/angular-gridster2#265]
There is a way to make the grid growing vertically without vertical inside scroll?
Basically, I wanna a full page scroll instead. In the original version, the grid height grows based on the rows generated (the grid height was updated programmatically).

**Comment by tiberiuzuld** [comment]
Hi @skarface ,

Currently that is not possible because the items are positioned absolute. 
This way the gridster element doesn't have any content height.
That is why the gridster has set 100% height of the parent container.

In version 5.x after the migration to CSS Grid this will be possible.

Thanks

**Comment by tiberiuzuld** [comment]
From the `initCallback` of the grid you get the gridster component 
On the component is set the property rows which is the total rows in grid.
You need to get it each time it changes so on each `itemChangeCallback`

**Comment by skarface** [comment]
Great @tiberiuzuld, thank you very much for the help.
