### ISSUE TITLE
itemInitCallbacks not fired for grid with height 0

### ISSUE THREAD

**Issue by celloman** [tiberiuzuld/angular-gridster2#276]
When initializing a grid (for a dashboard), the itemInitCallback isn't fired when the grid's height is 0 (or even very small, like 10px). We use this callback to calculate the appropriate grid height, so having it fire reliably is very important. For a workaround I am now setting the minHeight on the grid to 100px, but this isn't really the best fix and I don't know if it is the right way to fix it.

Any help/insight would be much appreciated.

Using Gridster 4.4.2 and Angular 5.2.1

**Comment by tiberiuzuld** [comment]
That is intentional not to fire if grid height is 0.
Because some people want to use that when to render they're inside components and want the items to have height.
Because of how angular and position absolute works the issue happens that the the first time when put in DOM the elements have 0 height.

**Comment by celloman** [comment]
That makes sense, I'm using it to do something similar, where I use the grid width to calculate an appropriate height to make sure my grid is composed of squares, but why wasn't it firing even if the min height was low, like 10px?

**Comment by tiberiuzuld** [comment]
Good question, probably because the item will be 0 because of `gridOptions.margin`

**Comment by celloman** [comment]
Ah, genius! Thanks for the help @tiberiuzuld, I really appreciate how responsive you are!
