### ISSUE TITLE
Size grid based on content

### ISSUE THREAD

**Issue by CollinGraf314** [tiberiuzuld/angular-gridster2#292]
Enhancement Request: Create an option that allows the gridster element's height to be determined by it's content, given that the gridType is either 'fixed', 'vertical fixed', or 'horizontal fixed'. 

In my case, I would like to allow the elements in my 'vertical fixed' grid to fill a space larger than the current screen size without creating multiple scroll-bars or defining a massive space for it to begin with.

If there is any known work around for getting this functionality, please let me know.

**Comment by tiberiuzuld** [comment]
Hi @CollinGraf314 ,
It's not possible because the elements are positioned absolute.
And because how position absolute works there is not possible for the grid element to increase in size automatically by the browser.

A workaround for now is to:
There is the option to determine the grid size on each `itemChangeCallback`, check the number of rows the grid and multiply by the fixed height, add margins and set the size on the grid.

Maybe in the future will add this option in the library.
Need to think about it.

**Comment by CollinGraf314** [comment]
Thanks for responding so fast, and thanks for the work around!

**Comment by tiberiuzuld** [comment]
Added in v5.3.0
