### ISSUE TITLE
Resize drag corner location on items with scroll 

### ISSUE THREAD

**Issue by CollinGraf314** [tiberiuzuld/angular-gridster2#337]
Assume you have a GridsterItem on your grid which has overflow-y set to scroll, and the content in that item is taller than the item itself. When attempting to resize the item, the grey triangle that is always supposed to sit in the bottom right corner of the item will rise as you scroll down.

![angular-gridster2](https://user-images.githubusercontent.com/9330290/40015870-aaf939b8-5782-11e8-99cd-aa644806a6bf.gif)

This is not an important issue, I would recommend putting it on the back burner. Just wanted to bring it to your attention. Especially since the fix isn't just as simple as changing `position: absolute` to `position: fixed`. I tried it :'(

**Comment by tiberiuzuld** [comment]
Hi @CollinGraf314 ,
Don't put the scroll on the gridster-item element,
Put it on a child then the corner will stay in it place.

**Comment by gabrielstefanescu** [comment]
Hi @tiberiuzuld,
I had the same issue as @CollinGraf314 , but after that I put a container inside and put a scroll on that. But there is an other issue, on Chrome it works well. But on the rest, the scrollbar is overlapping about half or maybe more of the scrollbar. So it's pretty difficult to actually scroll instead of resizing. Is there something that you would suggest to solve this?
Thanks, and good job, by the way.

**Comment by gabrielstefanescu** [comment]
never mind, adding a margin of 8px solved it, and now the resize is not overlapping the scrollbar. Also made a mistake in my previous post, it was the resize handle that overlapped the scrollbar. Thanks
