### ISSUE TITLE
Methods not defined in GridsterItemComponent

### ISSUE THREAD

**Issue by Pradeepg21** [tiberiuzuld/angular-gridster2#356]
Hi,

I am using angular-gridster2 library in my application and now tried to implement maximize and minimize option but while doing this when I tried to use _this.itemToPush.checkItemChanges(this.itemToPush.$item, this.itemToPush.item);_ 
![gridsteritemcomponent](https://user-images.githubusercontent.com/35950374/40839922-2ddba616-65c2-11e8-8328-26d1745b9572.PNG)
I saw that method _checkItemChanges_ is not defined inside GridsterItemComponent.

Please help

**Comment by Pradeepg21** [comment]
Hi,

Please help, I just want to implement maximize and minimize button.
and my dashboard is 
this.dashboard = [
      { cols: 6, rows: 2, y: 0, x: 0, title: "aaa" },
      { cols: 6, rows: 2, y: 0, x: 6, title: "bbb" },
      { cols: 6, rows: 2, y: 1, x: 0, title: "ccc" },
      { cols: 6, rows: 2, y: 1, x: 6, title: "ddd" },
      { cols: 6, rows: 2, y: 2, x: 0, title: "eee" },
      { cols: 6, rows: 2, y: 2, x: 6, title: "fff" }
    ];

Thanks

**Comment by CollinGraf314** [comment]
I apologize for how delayed my response to this was. 

What functionality did you want to get out of your maximize/minimize button?
One way to go about it would be to simply save the item's current position, then give it a high z-index and {cols: MAX_COLS, rows: MAX_ROWS, y: 0, x: 0} so that it covers the whole grid, and then display a minimize button so that reverts it back. 
Another way to go (I actually use this) is, similar to above) set the dimensions of the expanded widget and save the original position in a variable, and then iterate over the all the other items in your dashboard and add the number of rows the expanded item has to each other items y value, which simply shifts them down. 
If you want to use the Push Api to get this functionality, you can. I however do not have much experience with it and cannot give you any helpful tips.
