### ISSUE TITLE
$window.addResizeListener is not a function

### ISSUE THREAD

**Issue by karanaditya993** [tiberiuzuld/angular-gridster2#36]
Hello, 

Working on implementing gridster2 for angular 1 version. Demo looked great and does pretty much exactly what I want...however, after setting up the env with all the correct files, injecting dependencies, etc., getting three errors in console that I'm not sure I can explain/resolve. Wondering if you have seen these before? Errors are: 

$window.addResizeListener is not a function for line 774 in gridster.js (looks like there isn't that function on $window object)

Cannot read property 'addClass' of undefined for line 830 in gridster.js (looks like vm.element is undefined)

Thanks very much.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
The first error it seems because you don't have `javascript-detect-element-resize` as a dependency.
Second error is caused by the first one. Since the element is set after line `774`. 

If you already have : `<script src="bower_components/javascript-detect-element-resize/detect-element-resize.js"></script>`
Then I don't know what's the issue. That function is created by that library.

Let me know if this helps.

**Comment by karanaditya993** [comment]
@tiberiuzuld errors are fixed now after dependency injection, but UI is completely off (no tiles showing, just a gray bar across the top of the dashboard)...this probably has to do with my HTML and/or the way in which I declared scope objects. I'll keep working on this. Thanks again for your help

**Comment by tiberiuzuld** [comment]
@karanaditya993 probably css height of the grid element.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
The issue got resolved do you need any more help ?

**Comment by karanaditya993** [comment]
@tiberiuzuld shouldn't the height and all css for the grid be in the gridster.css file?

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
Yes all the css is in gridster.css 
The gridster has width and height 100% so will take the space the parent will give.
You can override the library css to give fixed px dimensions or use flex or what you prefer.
If you are messing with the demo and drag is not working check if not the compact up/left options are enabled and gives the sensation you cannot drag.

**Comment by karanaditya993** [comment]
Hey @tiberiuzuld thanks for the quick response. I think i'll end up using flex to configure the size and layout, but I'm actually not messing with the demo. I'm using the gridster.js and css files directly so I don't have compact options, and the drag functionality still doesn't seem to be working

**Comment by tiberiuzuld** [comment]
Hey @karanaditya993 ,
Very strange. The [drag default option](https://github.com/tiberiuzuld/angular-gridster2/blob/1.x/src/gridster2/gridster.constant.js) is false. 
But if you already put it on true then I don't know why is not working.
You will have to do some debugging in the source files to find the issue since I can't reproduce the issue.

**Comment by karanaditya993** [comment]
Didn't realize the default was false, setting to true fixed it (thank you). Yea I think I'll mess around with the css files to cater to my layout. We can close this issue out. Thanks very much again for all your help.

**Comment by tiberiuzuld** [comment]
Yey, good to hear.
Your welcome.
