### ISSUE TITLE
items overlap 

### ISSUE THREAD

**Issue by rawul** [tiberiuzuld/angular-gridster2#383]
I have a 4 by 4 grid and by clicking the arrow in bottom right corner the item expands to 2x2.(they are initialy 1x1). This seems to be happening
<img width="1468" alt="screen shot 2018-07-04 at 15 32 39" src="https://user-images.githubusercontent.com/18036658/42277365-ca97350a-7f9f-11e8-9b1e-45024894ad6c.png">
<img width="1467" alt="screen shot 2018-07-04 at 15 32 54" src="https://user-images.githubusercontent.com/18036658/42277366-cab75ba0-7f9f-11e8-8f49-ab7a8559895a.png">

**Comment by CollinGraf314** [comment]
If I am reading this properly, that grey arrow is a button you made and not the default gridster resize handle. Then when a person clicks that button you run a function that increments the rows and cols of the item the button is on. If this is the case, then of course the gridsterItems would overlap, which is expected behavior because you are not handling the collisions with the either gridsters push api or with custom logic. I am not terribly familiar with the push api, but as far as custom logic goes, simply loop through the items in your grid and increment the y value of any item that would be in a now compromised location.
