### ISSUE TITLE
source code of the demo app

### ISSUE THREAD

**Issue by dedalusmax** [tiberiuzuld/angular-gridster2#4]
The library is awesome! Is there any way to get the source code for the demo app? I hope it's angular 2 + webpack, since we're using that.

**Comment by tiberiuzuld** [comment]
Hi @dedalusmax 
Working on migrating to angular2
The migration of the core library code is done still need to figure out how to build and deploy as a library, since angular-cli at this moment doesn't offer that option.
Will probably have to move to another build system.

Hopefully will finish it this weekend.

**Comment by tiberiuzuld** [comment]
Hi @dedalusmax 
The demo app you can find [here](https://tiberiuzuld.github.io/angular-gridster2/angular/) 
The builded demo app code is [here](https://github.com/tiberiuzuld/angular-gridster2/tree/gh-pages/angular) 
The source code of the demo app is [here](https://github.com/tiberiuzuld/angular-gridster2/tree/master/src)

Let me know if you find any problems using the library.
Good luck :)

**Comment by dedalusmax** [comment]
i will test it and let you know the results. thank you for your fast response!
