### ISSUE TITLE
Column Scroll Mode (Trello'ish)

### ISSUE THREAD

**Issue by scottstcyr** [tiberiuzuld/angular-gridster2#422]
I am trying to use gridster2 to implement a Trello-like board.  The only area that doesn't work well is the vertical scrolling.  With Trello, the grid is confined to a fixed height and each column scrolls independently.  Otherwise, if you have columns with lots of data you can't effectively drag cards to other columns without placing them at the very bottom.  Losing the visibility of all of the columns as you scroll down just doesn't work cleanly in that scenario.

I would love to see a fixed column width mode that would invoke scroll bars at the column level rather than the grid level.  This would make the component very well suited for the Trello'ish use case.

**Comment by tiberiuzuld** [comment]
Hi @scottstcyr ,

What you describe is a very complex change to be able to have scroll independent for each column.
Instead I am proposing something more achievable: 

1. Use one grid per column configured with only one column.
For this to work the drag and drop from one grid to the other needs to work.
Current implementation of drag and drop directly is permitted only inside a grid, NOT outside in another grid. https://github.com/tiberiuzuld/angular-gridster2/issues/245 this issue discussions the issue around it.
Currently you can obtain this by doing a bit more work to outside the library and to use HTML5 drag and drop where you add draggable to each widget and use the option `emptyCellDropCallback`  
Example here: https://tiberiuzuld.github.io/angular-gridster2/emptyCell

2. Instead of using this library which is 2 dimensional and is created for something else than what you want, you could use one which is more suited for your use case.
In essence you have multiple lists(columns) of tasks which you want to move from one to another in a specific order.

I found these which I think are more suitable:
https://github.com/misha130/ngx-drag-and-drop-lists
https://www.npmjs.com/package/ngx-drag-drop

Let me know what you think and if you still need this library to have implemented the issue #245 

Thanks,
