### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by dzhavat** [tiberiuzuld/angular-gridster2#59]
Hey, thanks for building this grid. It's really good.

I've decided to give it a try in one project where I have a couple of widgets (`gridster-item`s) with some content in them. In some cases, whenever the content is bigger than the widget (`gridster-item`)'s height, scrollbars appear.

It looks like whenever I scroll the widget (and change detection runs) one small portion of `gridster`'s code runs and causes style recalculation, which in turn makes the page feel sluggish.

Here are a couple of screenshots.

![performance 2](https://user-images.githubusercontent.com/1096332/26981499-aea73428-4d35-11e7-9c1d-9da5f6d44b1d.PNG)

![problem](https://user-images.githubusercontent.com/1096332/26980538-c988276e-4d32-11e7-90cf-811a8ecb6a5c.PNG)

You can see from the screenshots that line 42 in `gridster.component` is called several times. Seems like the problem is in ngDoCheck hook. I tried removing the code entirely from it and everything continued to work. Why do you need it for and can one get away without it?

Hope you have time to look into the problem. If you have a plunkr running the grid I can try reproducing the issue. Thanks :)

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
The hook is used when the height/width of the element is changed without changing the window size.
There is no way to detect when the size is changed of a DOM element.
The check shouldn't be that heavy since only when the size is changed the resize of widgets is done.

I could introduce an option to not run the check if a user thinks he doesn't need it.

I will also have a look on the demo performance bottlenecks.

**Comment by dzhavat** [comment]
The thing is that I'm not resizing the height/width of the `gridster-item`. I just scroll the content and `ngDoCheck()` runs. If you see the docs about this hook it says that it's `Called during every change detection run`. So if CD runs anywhere in the app, this method will run as well and it might become a problem (as you can see in the first screenshot).

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Yes the `ngDoCheck` runs all the time that why I used it to detect change in size of the `gridster` element.
There are a couple options:
* keep it as it is
* find another way to detect DOM size change
* use only the `window resize`
* make available a api callback to be called from outside when the app knows it changed the size of the grid

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Removed the `ngDoCheck` check out v3.0.0.
Will have to call `this.options.api.resize` when needed.

Let me know if you still have performance problems.

**Comment by dzhavat** [comment]
Thanks for your effort. 👍 

I'll give it a try this week and get back to you with my findings.

**Comment by reppners** [comment]
@tiberiuzuld you might want to check out https://github.com/wnr/element-resize-detector to detect element resize changes

**Comment by tiberiuzuld** [comment]
Hi @reppners ,
Thank you for the suggestion will have a look.

**Comment by tiberiuzuld** [comment]
Hi @reppners ,
Looked over it and seems pretty heavy and the code is pretty massive. 
On first look seems to check element `offsetWidth/offsetHeight` on scroll event.

I think will keep it like this. 
Since there are few cases where is needed to resize the gridster when the window is not resized and the application will need to know to call `api.resize()`.

If anyone comes with an issue that he needs this for a very specific case that cannot be resolved from the application will review again then.

Thanks,

**Comment by darklinki** [comment]
I had a similar situation, you have to be carefull checking with offsetWidth leeds also to performance problems. Its mostly better to store the width/height of both the previous state and the new one. In ngDoCheck just Check if the previous and the new one are  different. Than add a ngAfterViewInit which sets the variables back. The good thing is ngAfterViewInit only runes once. I made it a little bit more complex arround 30 lines but it works like a charm in any situation.

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,

I assume the issues are resolved since there is no more activity in this thread.

Thanks,

**Comment by dzhavat** [comment]
@tiberiuzuld I tried v3.1.0 yesterday afternoon and everything worked just fine. Good job fixing the problem!

Thanks :)
