### ISSUE TITLE
Bug: Double Scroll bars for gridType ScrollVertical

### ISSUE THREAD

**Issue by ea20140129** [tiberiuzuld/angular-gridster2#651]
Hello Tiberiu:

When gridtype is set to ScrollVertical, double scroll bars appear when the browser is Not at it's maximum size (the browser window is smaller than the display area).

My GridsterConfig settings are as follows:
    gridType: GridType.ScrollVertical,
    disableWindowResize: true, // Set to true so that the widgets resize with zoom-in/zoom-out.
    setGridSize: false, // Set to false so that the widgets resize with zoom-in/zoom-out.
    keepFixedHeightInMobile: true,
    fixedRowHeight: -1, // makes widget fit content

This was reported as being fixed but doesn't seem to be.  I am currently using "version": "10.1.2".  Is there a way to have just one vertical scroll bar for ScrollVertical?

Appreciate your help with this.

**Comment by ea20140129** [comment]
Hello Tiberiu:

You will have to confirm; For ScrollVertical, The only way to have one scroll is for the scroll to be part of the grid and not a browser scroll?  In the index.html, I set the body with style="overflow: hidden;" to remove the browser scroll leaving just the grid scroll.

Appreciate your input on this.

**Comment by tiberiuzuld** [comment]
Hello @ea20140129 ,
What was fixed was the combinations of  `setGridSize: true` with `gridType`'s
`disableWindowResize` will disable resize of items based on available space.
When you zoom in and out with `Ctrl` + `Mouse Wheel` the items will not resize rest of content will. If you look with the dev tools inspector you will see that the items keep the same size in px.

If you have `setGridSize: false` the grid will try to take the available space from parent elements, that's why it has width and height 100% and will calculate rows/cols sizes based on that.

**Comment by ea20140129** [comment]
Hello Tiberiu:
I appreciate the details.  Unfortunately, those configurations won't work for the characteristics I am expecting.
