### ISSUE TITLE
setGridSize true unexpected behaviour

### ISSUE THREAD

**Issue by wessamyaacob** [tiberiuzuld/angular-gridster2#665]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21978069/91632804-98e1bc00-e9e3-11ea-920c-cadf79e97a3d.gif)

Hi , I tired to set setGridSize=true and use GridType Fixed and as you can see the scrolling bar is not working probably! am I doing something wrong ?

**Comment by tiberiuzuld** [comment]
Hi @wessamyaacob ,
I was unable to reproduce your issue in Edge/Firefox/Chrome on WIn10
What browser / OS you are using ?

**Comment by wessamyaacob** [comment]
Chrome on Win 10

**Comment by tiberiuzuld** [comment]
Ok I finally managed to reproduce it when on smaller resolution ...
I will investigate hope, I will find a fix for it.

Thanks

**Comment by tiberiuzuld** [comment]
So I found the issue. Very strange one indeed.
So the class `.gridSize` has a styling `overflow: hidden;`, if I remove this styling everything works fine.
If I put in place `overflow-x: hidden; overflow-y: hidden;` is still same effect.
The class `.fit` has the same styling does not create this issue.

Right now I am still searching for some workarounds because the issue seems to be a browser one, I was able to reproduce this in Firefox also. 

If I just remove the `overflow:hidden` when dragging or resize will look bad.

**Comment by tiberiuzuld** [comment]
Also if I remove the 
```css
  height: initial;
  width: initial;
```
will fix the issue.
But also this will create other side effects which are not wanted.

**Comment by tiberiuzuld** [comment]
I had to remove the `overflow:hidden` is the least downside of this fix, couldn't find any other workaround
now with `setGridSize: true` when drag/resize the items will render outside the grid 
you can try yourself to set `.gridSize { overflow: hidden;}` if you don't have scroll and want to clip that.

**Comment by tiberiuzuld** [comment]
Deployed to npm the fix in v10.1.5
